import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Loader2, MessageCircle } from "lucide-react";

interface Props {
  cert: any | null;
  onClose: () => void;
  var1: string; onVar1Change: (v: string) => void;
  var2: string; onVar2Change: (v: string) => void;
  var3: string; onVar3Change: (v: string) => void;
  isSending: boolean;
  onSend: () => void;
}

export function BatchIndivWaModal({ cert, onClose, var1, onVar1Change, var2, onVar2Change, var3, onVar3Change, isSending, onSend }: Props) {
  return (
    <Dialog open={!!cert} onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Send via WhatsApp — {cert?.recipientName}</DialogTitle>
          <DialogDescription>
            Uses the <strong>document_senderv2</strong> template.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <div className="bg-secondary/30 rounded-xl p-4 border border-border/50 text-sm font-mono text-muted-foreground">
            Hi <span className="text-foreground font-semibold">{var1 || "{{1}}"}</span>, your certificate for <span className="text-foreground font-semibold">{var2 || "{{2}}"}</span> is attached below. you can always download this certificate by sending /cert to this bot. you can visit www.cephloe.com/<span className="text-foreground font-semibold">{var3 || "{{3}}"}</span> it will act as a profile where you can see all your event certificates generated by Caphloe
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{"{{1}}"} — Participant Name</label>
            <Input value={var1} onChange={e => onVar1Change(e.target.value)} placeholder="e.g. <<Name>>" />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{"{{2}}"} — Event Name</label>
            <Input value={var2} onChange={e => onVar2Change(e.target.value)} placeholder="e.g. batch name" />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">{"{{3}}"} — Email Prefix (Profile URL)</label>
            <Input value={var3} onChange={e => onVar3Change(e.target.value)} placeholder="e.g. <<EmailPrefix>>" />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>Cancel</Button>
          <Button onClick={onSend} disabled={isSending || !var1 || !var2}>
            {isSending ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <MessageCircle className="w-4 h-4 mr-2" />}
            Send via WhatsApp
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
