import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Loader2, MessageCircle } from "lucide-react";

interface Props {
  open: boolean;
  onOpenChange: (o: boolean) => void;
  var1: string; onVar1Change: (v: string) => void;
  var2: string; onVar2Change: (v: string) => void;
  var3: string; onVar3Change: (v: string) => void;
  isSending: boolean;
  onSend: () => void;
  batchName: string;
  rowDataHeaders: string[];
}

export function BatchSendWaModal({ open, onOpenChange, var1, onVar1Change, var2, onVar2Change, var3, onVar3Change, isSending, onSend, batchName, rowDataHeaders }: Props) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[700px]">
        <DialogHeader>
          <DialogTitle>Send via WhatsApp</DialogTitle>
          <DialogDescription>
            Uses the <strong>document_senderv2</strong> template. The PDF certificate will be attached and sent to each recipient's phone number.
          </DialogDescription>
        </DialogHeader>
        <div className="grid md:grid-cols-3 gap-6 py-4">
          <div className="md:col-span-2 space-y-4">
            <div className="bg-secondary/30 rounded-xl p-4 border border-border/50 text-sm font-mono text-muted-foreground mb-2">
              Hi <span className="text-foreground font-semibold">{var1 || "{{1}}"}</span>, your certificate for <span className="text-foreground font-semibold">{var2 || "{{2}}"}</span> is attached below. you can always download this certificate by sending /cert to this bot. you can visit www.cephloe.com/<span className="text-foreground font-semibold">{var3 || "{{3}}"}</span> it will act as a profile where you can see all your event certificates generated by Caphloe
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">{"{{1}}"} — Participant Name</label>
              <Input value={var1} onChange={e => onVar1Change(e.target.value)} placeholder="e.g. <<Name>>" className="transition-all duration-200"
                onDragOver={(e) => { e.preventDefault(); e.dataTransfer.dropEffect = "copy"; (e.target as HTMLInputElement).focus(); }}
                onDrop={(e) => { e.preventDefault(); const text = e.dataTransfer.getData("text/plain"); if (text) onVar1Change(text); }}
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">{"{{2}}"} — Event Name</label>
              <Input value={var2} onChange={e => onVar2Change(e.target.value)} placeholder="e.g. batch name or <<EventName>>" className="transition-all duration-200"
                onDragOver={(e) => { e.preventDefault(); e.dataTransfer.dropEffect = "copy"; (e.target as HTMLInputElement).focus(); }}
                onDrop={(e) => { e.preventDefault(); const text = e.dataTransfer.getData("text/plain"); if (text) onVar2Change(text); }}
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">{"{{3}}"} — Email Prefix (Profile URL)</label>
              <Input value={var3} onChange={e => onVar3Change(e.target.value)} placeholder="e.g. <<EmailPrefix>>" className="transition-all duration-200"
                onDragOver={(e) => { e.preventDefault(); e.dataTransfer.dropEffect = "copy"; (e.target as HTMLInputElement).focus(); }}
                onDrop={(e) => { e.preventDefault(); const text = e.dataTransfer.getData("text/plain"); if (text) onVar3Change(text); }}
              />
            </div>
          </div>

          <div className="space-y-4">
            <div className="bg-secondary/30 rounded-xl p-4 border border-border/50 h-full">
              <label className="text-sm font-semibold mb-3 block">Placeholders</label>
              <p className="text-[10px] text-muted-foreground mb-3">Drag and drop to insert</p>
              <div className="flex flex-wrap gap-2 overflow-y-auto max-h-[250px] pr-1">
                <div
                  draggable
                  onDragStart={(e) => { e.dataTransfer.setData("text/plain", batchName); e.dataTransfer.effectAllowed = "copy"; }}
                  className="bg-background border border-border hover:border-primary/50 hover:bg-primary/5 text-foreground px-2 py-1 rounded-md text-[11px] font-mono cursor-grab active:cursor-grabbing transition-all flex items-center gap-1.5 group shadow-sm"
                >
                  <div className="w-1 h-1 rounded-full bg-primary/40 group-hover:bg-primary transition-colors" />
                  Batch Name
                </div>
                {rowDataHeaders.map(header => (
                  <div
                    key={header}
                    draggable
                    onDragStart={(e) => { e.dataTransfer.setData("text/plain", `<<${header}>>`); e.dataTransfer.effectAllowed = "copy"; }}
                    className="bg-background border border-border hover:border-primary/50 hover:bg-primary/5 text-foreground px-2 py-1 rounded-md text-[11px] font-mono cursor-grab active:cursor-grabbing transition-all flex items-center gap-1.5 group shadow-sm"
                  >
                    <div className="w-1 h-1 rounded-full bg-primary/40 group-hover:bg-primary transition-colors" />
                    {header}
                  </div>
                ))}
                {rowDataHeaders.length === 0 && (
                  <div className="text-[10px] text-muted-foreground italic text-center w-full py-4">No data fields available.</div>
                )}
              </div>
            </div>
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button onClick={onSend} disabled={isSending || !var1 || !var2}>
            {isSending ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <MessageCircle className="w-4 h-4 mr-2" />}
            Send via WhatsApp
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
