import { Router, type IRouter } from "express";
import { supabaseAdmin } from "@workspace/supabase";

const router: IRouter = Router();

interface WaReport {
  id: number;
  phone: string;
  cert_key?: string;
  message: string;
  created_at: string;
}

router.get("/reports", async (req, res): Promise<void> => {
  const userId = req.user?.uid;
  if (!userId) {
    res.status(401).json({ error: "Unauthorized" });
    return;
  }

  const workerUrl = process.env.WA_WORKER_URL || process.env.VITE_WA_WORKER_URL;
  const token = process.env.WA_ANALYTICS_TOKEN || process.env.VITE_WA_ANALYTICS_TOKEN;
  if (!workerUrl || !token) {
    res.status(503).json({ error: "Reports not configured." });
    return;
  }

  try {
    // Fetch all reports from the WA worker (server-side token, never exposed to clients)
    const waRes = await fetch(`${workerUrl.replace(/\/$/, "")}/reports?token=${token}`);
    if (!waRes.ok) throw new Error(`WA worker responded ${waRes.status}`);
    const allReports: WaReport[] = await waRes.json();

    if (allReports.length === 0) {
      res.json([]);
      return;
    }

    // Get all certs generated by this user so we can filter reports to theirs only
    const { data: batches } = await supabaseAdmin
      .from("batches")
      .select("id")
      .eq("user_id", userId);

    if (!batches || batches.length === 0) {
      res.json([]);
      return;
    }

    const batchIds = batches.map((b) => b.id);

    const { data: certs } = await supabaseAdmin
      .from("certificates")
      .select("r2_pdf_url")
      .in("batch_id", batchIds)
      .not("r2_pdf_url", "is", null);

    if (!certs || certs.length === 0) {
      res.json([]);
      return;
    }

    // cert_key from the WA worker is the trailing path segment(s) of the R2 URL
    // e.g. cert_key = "918123456789/John_Doe_Batch.pdf"
    //      r2_pdf_url = "https://r2.example.com/918123456789/John_Doe_Batch.pdf"
    const r2Urls = new Set(certs.map((c) => c.r2_pdf_url as string));

    const filtered = allReports.filter((r) => {
      if (!r.cert_key) return false;
      for (const url of r2Urls) {
        if (url.endsWith(r.cert_key)) return true;
      }
      return false;
    });

    res.json(filtered);
  } catch (err: any) {
    console.error("[reports] fetch failed:", err);
    res.status(500).json({ error: "Failed to load reports." });
  }
});

export default router;
